[package]
name = "internode"
version = "0.0.5"
edition = "2021"

[dependencies]
ndarray = "0.15.0"
clap = { version = "3.1.8", features = ["derive"] }

[build-dependencies]
bindgen = "0.59.2"
cc = "1.0.73"

[[bin]]
name = "wastrid"
path = "src/main.rs"