[package]
name = "internode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.0"

[build-dependencies]
bindgen = "0.59.2"
cc = "1.0.73"